# Generated by Django 4.2.4 on 2023-11-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
